INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Австралия', ' 61');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Австрия', ' 43');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Азербайджан', ' 994');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Албания', ' 355');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Алжир', ' 213');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Ангола', ' 244');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Андорра', ' 376');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Антигуа и Барбуда', ' 1268');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Аргентина', ' 54');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Армения', ' 374');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Афганистан', ' 93');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Багамы', ' 1242');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Бангладеш', ' 880');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Барбадос', ' 1246');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Бахрейн', ' 973');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Беларусь', ' 375');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Белиз', ' 501');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Бельгия', ' 32');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Бенин', ' 229');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Болгария', ' 359');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Боливия', ' 591');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Босния и Герцеговина', ' 387');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Ботсвана', ' 267');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Бразилия', ' 55');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Бруней', ' 673');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Буркина Фасо', ' 226');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Бурунди', ' 257');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Бутан', ' 975');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Вануату', ' 678');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Ватикан', ' 39');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Великобритания', ' 44');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Венгрия', ' 36');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Венесуэла', ' 58');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Восточный Тимор', ' 670');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Вьетнам', ' 84');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Габон', ' 241');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Гаити', ' 509');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Гайана', ' 592');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Гамбия', ' 220');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Гана', ' 233');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Гватемала', ' 502');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Гвинея', ' 224');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Гвинея-Бисау', ' 245');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Германия', ' 49');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Гондурас', ' 504');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Гренада', ' 1473');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Греция', ' 30');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Грузия', ' 995');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Дания', ' 45');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Джибути', ' 253');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Доминика', ' 1767');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Доминиканская Республика', ' 1809');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Египет', ' 20');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Замбия', ' 260');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Зимбабве', ' 263');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Израиль', ' 972');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Индия', ' 91');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Индонезия', ' 62');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Иордания', ' 962');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Ирак', ' 964');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Иран', ' 98');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Ирландия', ' 353');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Исландия', ' 354');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Испания', ' 34');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Италия', ' 39');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Йемен', ' 967');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Кабо-Верде', ' 238');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Казахстан', ' 77');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Камбоджа', ' 855');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Камерун', ' 237');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Канада', ' 1');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Катар', ' 974');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Кения', ' 254');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Кипр', ' 357');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Киргизия', ' 996');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Кирибати', ' 686');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Китай', ' 86');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Колумбия', ' 57');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Коморы', ' 269');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Конго, демократическая республика', ' 243');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Конго, республика ', ' 242');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Коста-Рика', ' 506');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Кот-д’Ивуар', ' 225');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Куба', ' 53');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Кувейт', ' 965');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Лаос', ' 856');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Латвия', ' 371');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Лесото', ' 266');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Либерия', ' 231');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Ливан', ' 961');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Ливия', ' 218');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Литва', ' 370');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Лихтенштейн', ' 423');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Люксембург', ' 352');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Маврикий', ' 230');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Мавритания', ' 222');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Мадагаскар', ' 261');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Македония', ' 389');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Малави', ' 265');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Малайзия', ' 60');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Мали', ' 223');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Мальдивы', ' 960');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Мальта', ' 356');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Марокко', ' 212');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Маршалловы Острова', ' 692');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Мексика', ' 52');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Мозамбик', ' 259');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Молдавия', ' 373');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Монако', ' 377');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Монголия', ' 976');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Мьянма', ' 95');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Намибия', ' 264');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Науру', ' 674');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Непал', ' 977');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Нигер', ' 227');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Нигерия', ' 234');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Нидерланды', ' 31');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Никарагуа', ' 505');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Новая Зеландия', ' 64');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Норвегия', ' 47');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Объединенные Арабские Эмираты', ' 971');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Оман', ' 968');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Пакистан', ' 92');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Палау', ' 680');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Панама', ' 507');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Папуа - Новая Гвинея', ' 675');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Парагвай', ' 595');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Перу', ' 51');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Польша', ' 48');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Португалия', ' 351');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Россия', ' 7');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Руанда', ' 250');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Румыния', ' 40');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Сальвадор', ' 503');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Самоа', ' 685');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Сан-Марино', ' 378');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Сан-Томе и Принсипи', ' 239');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Саудовская Аравия', ' 966');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Свазиленд', ' 268');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Северная Корея', ' 850');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Сейшелы', ' 248');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Сенегал', ' 221');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Сент-Винсент и Гренадины', ' 1784');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Сент-Китс и Невис', ' 1869');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Сент-Люсия', ' 1758');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Сербия', ' 381');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Сингапур', ' 65');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Сирия', ' 963');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Словакия', ' 421');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Словения', ' 986');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Соединенные Штаты Америки', ' 1');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Соломоновы Острова', ' 677');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Сомали', ' 252');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Судан', ' 249');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Суринам', ' 597');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Сьерра-Леоне', ' 232');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Таджикистан', ' 992');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Таиланд', ' 66');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Танзания', ' 255');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Того', ' 228');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Тонга', ' 676');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Тринидад и Тобаго', ' 1868');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Тувалу', ' 688');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Тунис', ' 216');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Туркмения', ' 993');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Турция', ' 90');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Уганда', ' 256');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Узбекистан', ' 998');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Украина', ' 380');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Уругвай', ' 598');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Федеративные штаты Микронезии', ' 691');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Фиджи', ' 679');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Филиппины', ' 63');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Финляндия', ' 358');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Франция', ' 33');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Хорватия', ' 385');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Центрально-Африканская Республика', ' 236');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Чад', ' 235');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Черногория', ' 381');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Чехия', ' 420');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Чили', ' 56');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Швейцария', ' 41');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Швеция', ' 46');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Шри-Ланка', ' 94');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Эквадор', ' 593');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Экваториальная Гвинея', ' 240');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Эритрея', ' 291');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Эстония', ' 372');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Эфиопия', ' 251');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Южная Корея', ' 82');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Южно-Африканская Республика', ' 27');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Ямайка', ' 1876');
INSERT INTO CountryCode([Country], [InternCode]) VALUES (N'Япония', ' 81');
